[package]
name = "graphql-2-ts"
version = "0.1.0"
edition = "2021"
description = "Generate Typescript according to a GraphQL schema."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
